spring:
  datasource:
    initialization-mode: never
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library
    username: library
    password: qAF219x

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
server:
  port: 8000